services:
  api:
    container_name: quiz_api
    expose:
      - 5001
    ports:
      - 5001:5001
    environment:
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=quiz_db
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    container_name: quiz_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
volumes:
  dbdata:
networks:
  default:
    name: quiz_app
